### ISSUE TITLE
No such file or directory error on yolo_tf_converter.py script

### ISSUE THREAD

**Issue by Fonta88** [AlessioTonioni/tf-objdetector#1]
Good afternoon,

I'm facing the following error while running yolo_tf_converter.py script

Traceback (most recent call last):
  File "yolo_tf_converter.py", line 149, in <module>
    convert_yolo_tf(args.trainingList, args.outputTfRecord,args.labelMap, args.classNameFile)
  File "yolo_tf_converter.py", line 119, in convert_yolo_tf
    example = get_tf_record(f.strip(), l, class_names)
  File "yolo_tf_converter.py", line 32, in get_tf_record
    encoded_img = fid.read()
  File "/home/ppp/.local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 122, in read
    self._preread_check()
  File "/home/ppp/.local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: ~/myFolder/darknet/darknet/custom_data/images/1310154281.04-foto.jpg; No such file or directory

The file exists in the correct folder, I can move it with mv command.
Here the complete command

python3 yolo_tf_converter.py -t ~/myFolder/darknet/darknet/custom_data/traininglist.txt -o ~/myFolder/darknet/darknet/custom_data/a.tfrecord -c ~/myFolder/darknet/darknet/custom_data/className.txt

What is wrong?
Thanks in advance

**Comment by AlessioTonioni** [comment]
remove '~' from the paths on the list and use the full path instead

**Comment by Fonta88** [comment]
It works, thanks for the support
